# Generated by Django 3.2.13 on 2022-05-10 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresatitularbeneficio',
            name='idempresatitular',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.empresatitular'),
            preserve_default=False,
        ),
    ]
